# Generated by Django 5.1.4 on 2025-01-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvRestaurante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='ubicacion',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidadMedida',
            field=models.CharField(max_length=30),
        ),
    ]
